basePath: /api/v1
definitions:
  core.ZError:
    properties:
      code:
        example: 500
        type: integer
      exception: {}
      message:
        example: Пример ошибки
        type: string
      where:
        example: ExampleAPI
        type: string
    type: object
  share.QConfirmEmail:
    properties:
      code:
        example: "123456"
        type: string
      signup_id:
        example: 592af5b5-4f60-4ddd-b080-be674c86eda8
        type: string
    type: object
  share.QEmailSignup:
    properties:
      confim_pwd:
        example: "123123"
        type: string
      email:
        example: user@example.com
        type: string
      password:
        example: "123123"
        type: string
    type: object
  share.QLoginEmail:
    properties:
      email:
        example: user@example.com
        type: string
      password:
        example: "123123"
        type: string
    type: object
  share.QRefreshToken:
    properties:
      refresh_token:
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NSIsImV4cCI6MTk5OTk5OTk5OSwiaWF0IjoxNzAwMDAwMDAwLCJpc3MiOiJleGFtcGxlLWFwcCJ9.rnH9fqOBlB4tfbgIhJX_yta9Z9yVtOmMFLhy5aC_cC8
        type: string
    type: object
  share.ZAccount:
    properties:
      created_at:
        example: "2024-02-13 05:37:40.483836"
        type: string
      email:
        example: user@example.com
        type: string
      id:
        example: 592af5b5-4f60-4ddd-b080-be674c86eda8
        type: string
      passwd_hash:
        type: string
      salt:
        type: string
      updated_at:
        example: "2024-02-13 05:37:40.483836"
        type: string
    type: object
  share.ZEmailSignup:
    properties:
      code:
        description: Добавлено для local debug
        example: "123456"
        type: string
      created_at:
        example: "2024-02-13 05:37:40.483836"
        type: string
      email:
        example: user@example.com
        type: string
      id:
        example: 592af5b5-4f60-4ddd-b080-be674c86eda8
        type: string
      passwd_hash:
        example: 592af5b54f604dddb080be674c86eda8
        type: string
      salt:
        example: 592af5b54f604dddb080be674c86eda8
        type: string
      updated_at:
        example: "2024-02-13 05:37:40.483836"
        type: string
    type: object
  share.ZToken:
    properties:
      bearer:
        example: Authefication
        type: string
      refresh_token:
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NSIsImV4cCI6MTk5OTk5OTk5OSwiaWF0IjoxNzAwMDAwMDAwLCJpc3MiOiJleGFtcGxlLWFwcCJ9.rnH9fqOBlB4tfbgIhJX_yta9Z9yVtOmMFLhy5aC_cC8
        type: string
      token:
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NSIsImV4cCI6MTk5OTk5OTk5OSwiaWF0IjoxNzAwMDAwMDAwLCJpc3MiOiJleGFtcGxlLWFwcCJ9.rnH9fqOBlB4tfbgIhJX_yta9Z9yVtOmMFLhy5aC_cC8
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: REST API for authentication
  title: Service API
  version: "1.0"
paths:
  /user/auth/confirm/email:
    post:
      consumes:
      - application/json
      parameters:
      - description: Данные подтверждения
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/share.QConfirmEmail'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/share.ZAccount'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/core.ZError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/core.ZError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/core.ZError'
      summary: Подтверждение регистрации
      tags:
      - Auth
  /user/auth/login/email:
    post:
      consumes:
      - application/json
      parameters:
      - description: Данные аккаунта
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/share.QLoginEmail'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/share.ZToken'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/core.ZError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/core.ZError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/core.ZError'
      summary: Вход в аккаунт через email
      tags:
      - Auth
  /user/auth/refresh/token:
    post:
      consumes:
      - application/json
      parameters:
      - description: Токен
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/share.QRefreshToken'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/share.ZToken'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/core.ZError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/core.ZError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/core.ZError'
      summary: Рефреш токена
      tags:
      - Auth
  /user/auth/signup/email:
    post:
      consumes:
      - application/json
      parameters:
      - description: Данные регистрации
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/share.QEmailSignup'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/share.ZEmailSignup'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/core.ZError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/core.ZError'
      summary: Регистрация пользователя
      tags:
      - Auth
swagger: "2.0"
