services:
  app:
    container_name: app
    build:
      context: .
      args:
        ENV: "local"
    command: sh -c "go test ./... && ./server"
    volumes:
      - ./src:/src
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      medods-local:
        ipv4_address: 175.243.0.10
    depends_on:
    - postgres-db
  
  postgres-db:
    container_name: postgres-db
    image: postgres:16.1-alpine3.18
    command: "-c logging_collector=off"
    logging:
      driver: none
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres123}
      POSTGRES_HOST_AUTH_METHOD: trust
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "15432:5432"
    restart: unless-stopped
    networks:
      medods-local:
        ipv4_address: 175.243.0.50

volumes:
  db:
    driver: local

networks:
  medods-local:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 175.243.0.0/16