root = "."
tmp_dir = "tmp"

[build]
  cmd = "./gen_swagger_if_needed.sh && go build -o ./tmp/main ./app"
  bin = "tmp/main"
  include_ext = ["go"]
  exclude_dir = ["tmp", "vendor"]
  delay = 1000
  poll = true
  stop_on_error = true
  log = "build.log"

[log]
  time = true

[color]
  main = "yellow"
  watcher = "cyan"
  build = "green"
  runner = "magenta"
